name: Setup
description: Setup common stuff for jobs
inputs:
    node-version:
        description: Node.js version to install; defaults to .nvmrc
        required: false
        default: ""
runs:
    using: "composite"
    steps:
        - name: Setup environment
          shell: bash
          run: |
              NODE_VERSION="${{ inputs.node-version }}"
              if [[ -z "$NODE_VERSION" ]]; then
                  NODE_VERSION=$(cat .nvmrc | xargs)
              fi
              echo "node_version=$NODE_VERSION" >> $GITHUB_ENV

        - name: Setup node
          uses: actions/setup-node@v4
          with:
              node-version: ${{ env.node_version }}
              cache: npm
              registry-url: "https://registry.npmjs.org"

        - name: Install Dependencies
          run: npm ci
          shell: bash

        - name: Build Packages
          run: npm run build
          shell: bash
