steps:
  - command: "FIXTURE=kotlin,schema-kotlin,kotlin-jackson,schema-kotlin-jackson,graphql .buildkite/build-pr.sh"
    label: "C++ Kotlin GraphQL"

  - command: "FIXTURE=java,schema-java,schema-json-csharp .buildkite/build-pr.sh"
    label: "java schema-json-c#"

  - command: "FIXTURE=javascript,schema-javascript,flow,schema-flow,json-ts-csharp,python,schema-python .buildkite/build-pr.sh"
    label: "typescript javascript flow python"

  - command: "FIXTURE=swift,schema-swift,rust,schema-rust,elm,schema-elm,dart,schema-dart .buildkite/build-pr.sh"
    label: "swift rust elm dart"

  - command: "FIXTURE=csharp,schema-csharp,ruby,schema-ruby,golang,schema-golang,pike,schema-pike .buildkite/build-pr.sh"
    label: "csharp ruby golang pike"

  - command: "FIXTURE=haskell,schema-haskell,javascript-prop-types .buildkite/build-pr.sh"
    label: "haskell javascript-prop-types"
