#!/bin/bash

# This runs quicktype, ensuring dependencies are installed
# and rebuilding quicktype first.
#
# Use script/quickertype to skip reinstalling dependencies
# and rebuilding PureScript for 10s faster runs if you
# are just working on TargetLanguage code in TypeScript.

npm run build &>/dev/null
node --stack_trace_limit=100 dist/quicktype.js $@
