#!/bin/bash

set -eu

if [[ "$BUILDKITE_PULL_REQUEST" != "false" ]]; then
    # Build the merge commit of the PR
    git fetch origin "pull/$BUILDKITE_PULL_REQUEST/merge"
    git checkout -qf FETCH_HEAD
fi