name: Test Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fixture: [typescript, javascript]
    name: Test ${{ matrix.fixture }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: npm
      - run: npm ci
      - run: FIXTURE=${{ matrix.fixture }} npm test
